<?php

namespace frontEndBundle\Repository;

/**
 * InterventionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterventionsRepository extends \Doctrine\ORM\EntityRepository
{
}
