<?php

namespace frontEndBundle\Repository;

/**
 * VotesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VotesRepository extends \Doctrine\ORM\EntityRepository
{
}
