back_end:
    resource: "@backEndBundle/Controller/"
    type:     annotation
    prefix:   /

front_end:
    resource: "@frontEndBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
captcha_routing:
    resource: "@CaptchaBundle/Resources/config/routing.yml"